version: "1.0"

services:
  db:
    image: mongo:latest
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Redis (for BullMQ)
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # API Gateway
  api-gateway:
    build: ./apps/api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4000
      - PROBLEM_SERVICE_URL=http://problem-service:6000
      - SUBMISSION_SERVICE_URL=http://submission-service:4000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - auth-service
      - problem-service
      - submission-service
    networks:
      - app-network

  # Auth Service
  auth-service:
    build: ./apps/auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/ArenaDB
      - JWT_SECRET=your_jwt_secret_here
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - db
    networks:
      - app-network

  # Problem Service
  problem-service:
    build: ./problem-service
    container_name: problem-service
    ports:
      - "6000:6000"
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/ArenaDB
      - CLIENT_URL=http://localhost:5173
      - PORT=6000
    depends_on:
      - db
    networks:
      - app-network

  # Submission Service
  submission-service:
    build: ./submission-service
    container_name: submission-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/ArenaDB
      - SUBMISSION_SERVICE_PORT=4000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - db
      - worker-service
    networks:
      - app-network

  # Worker Service
  worker-service:
    build: ./worker-service
    container_name: worker-service
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/ArenaDB
      - NOTIFICATION_SERVICE_URL=http://notification-service:5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CLIENT_URL=http://localhost:5173
      - TIMEOUT_LIMIT=2000
      - MEMORY_LIMIT=268435456
    depends_on:
      - redis
      - db
      - notification-service
    networks:
      - app-network

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "5000:5000"
    environment:
      - CLIENT_URL=http://localhost:5173
      - NOTIFICATION_SERVICE_PORT=5000
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - db
    networks:
      - app-network

  # Client (Frontend)
  client:
    build: ./apps/client
    container_name: client
    ports:
      - "5173:5173"
    environment:
      - VITE_NOTIFICATION_SERVICE_URL=http://notification-service:5000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
